#!/usr/bin/env python
# -*- coding: utf-8 -*-

"""
Basic CPU & Memory Usage for Tmux

Author: Zaiste! <oh@zaiste.net>
Author: Jeff Dickey @dickeyxxx

Dash-meter inspired by tmux-mem-cpu
and code from psutil top.py.
"""

import os
import sys
if os.name != 'posix':
        sys.exit('platform not supported')
import psutil

def get_bar(perc):
    if perc < 5:
        return " "
    elif perc < 10:
        return "▁"
    elif perc < 20:
        return "▂"
    elif perc < 40:
        return "▃"
    elif perc < 60:
        return "▄"
    elif perc < 80:
        return "▅"
    else:
        return "▇"

def info():
    mem = psutil.virtual_memory()
    cpu = psutil.cpu_percent(interval=1)
    line = "%s/%sGB %.0f%% %s " % (
        str(int(mem.used / 1024 / 1024 / 1024)),
        str(int(mem.total / 1024 / 1024 / 1024)),
        cpu,
        get_bar(cpu),
    )
    return line


def main():
    try:
        print info()
    except (KeyboardInterrupt, SystemExit):
        pass

if __name__ == '__main__':
    main()
